"""
Pull request management for automation pipeline.

This module provides functionality for creating and managing
GitHub pull requests.
"""

import logging
from dataclasses import dataclass
from typing import List, Optional

logger = logging.getLogger(__name__)


@dataclass
class PRInfo:
    """Information about a pull request."""
    number: int
    title: str
    body: str
    head_branch: str
    base_branch: str
    html_url: str
    state: str = "open"
    draft: bool = False

    @classmethod
    def from_pull_request(cls, pr) -> "PRInfo":
        """Create PRInfo from PyGithub PullRequest object."""
        return cls(
            number=pr.number,
            title=pr.title,
            body=pr.body or "",
            head_branch=pr.head.ref,
            base_branch=pr.base.ref,
            html_url=pr.html_url,
            state=pr.state,
            draft=pr.draft,
        )


class PRManager:
    """
    Manages GitHub pull request operations.

    This class handles creating, updating, and managing pull requests
    for the automation pipeline.

    Example:
        >>> manager = PRManager(github_client)
        >>> pr = manager.create_pr(
        ...     repo="owner/repo",
        ...     title="Add login feature",
        ...     head="feat/issue-123-add-login",
        ...     body="Implements #123",
        ... )
    """

    def __init__(self, github_client):
        """
        Initialize the PR manager.

        Args:
            github_client: GitHubClient instance
        """
        self.github_client = github_client

    def create_pr(
        self,
        repo: str,
        title: str,
        head: str,
        base: str = "main",
        body: Optional[str] = None,
        draft: bool = False,
        issue_number: Optional[int] = None,
    ) -> PRInfo:
        """
        Create a pull request.

        Args:
            repo: Repository name in 'owner/repo' format
            title: PR title
            head: Source branch name
            base: Target branch name
            body: PR description
            draft: Whether to create as draft
            issue_number: Related issue number (for auto-linking)

        Returns:
            PRInfo for the created pull request
        """
        # Build PR body
        pr_body = body or ""
        if issue_number:
            pr_body = f"Closes #{issue_number}\n\n{pr_body}"
        
        # Add standard sections
        pr_body = self._enhance_pr_body(pr_body, issue_number)

        pr = self.github_client.create_pull_request(
            repo=repo,
            title=title,
            head=head,
            base=base,
            body=pr_body,
            draft=draft,
        )

        logger.info(f"Created PR #{pr.number}: {head} -> {base}")
        return PRInfo.from_pull_request(pr)

    def _enhance_pr_body(
        self,
        body: str,
        issue_number: Optional[int],
    ) -> str:
        """Add standard sections to PR body."""
        sections = [body]

        # Add automation footer
        sections.append("\n---\n")
        sections.append("*This PR was automatically generated by AI Harness.*")

        if issue_number:
            sections.append(f"\nRelated: #{issue_number}")

        return "\n".join(sections)

    def request_review(
        self,
        repo: str,
        pr_number: int,
        reviewers: List[str],
    ) -> None:
        """
        Request reviewers for a pull request.

        Args:
            repo: Repository name
            pr_number: PR number
            reviewers: List of reviewer usernames
        """
        self.github_client.request_review(
            repo=repo,
            pr_number=pr_number,
            reviewers=reviewers,
        )
        logger.info(f"Requested review from {reviewers} for PR #{pr_number}")

    def add_comment(
        self,
        repo: str,
        pr_number: int,
        comment: str,
    ) -> None:
        """Add a comment to a pull request."""
        self.github_client.add_pr_comment(
            repo=repo,
            pr_number=pr_number,
            comment=comment,
        )

    def get_pr_for_branch(
        self,
        repo: str,
        branch_name: str,
    ) -> Optional[PRInfo]:
        """
        Get open PR for a specific branch.

        Args:
            repo: Repository name
            branch_name: Head branch name

        Returns:
            PRInfo if found, None otherwise
        """
        prs = self.github_client.get_pull_requests(
            repo=repo,
            head=branch_name,
        )
        
        if prs:
            return prs[0]
        return None

    def update_pr(
        self,
        repo: str,
        pr_number: int,
        title: Optional[str] = None,
        body: Optional[str] = None,
        state: Optional[str] = None,
    ) -> PRInfo:
        """Update a pull request."""
        repository = self.github_client.get_repo(repo)
        pr = repository.get_pull(pr_number)
        
        kwargs = {}
        if title:
            kwargs["title"] = title
        if body:
            kwargs["body"] = body
        if state:
            kwargs["state"] = state
        
        if kwargs:
            pr.edit(**kwargs)
        
        return PRInfo.from_pull_request(pr)

    def merge_pr(
        self,
        repo: str,
        pr_number: int,
        commit_message: Optional[str] = None,
        merge_method: str = "squash",
    ) -> bool:
        """
        Merge a pull request.

        Args:
            repo: Repository name
            pr_number: PR number
            commit_message: Custom commit message
            merge_method: Merge method (merge, squash, rebase)

        Returns:
            True if merged successfully
        """
        repository = self.github_client.get_repo(repo)
        pr = repository.get_pull(pr_number)
        
        try:
            result = pr.merge(
                commit_message=commit_message,
                merge_method=merge_method,
            )
            if result.merged:
                logger.info(f"Merged PR #{pr_number}")
                return True
            else:
                logger.warning(f"PR #{pr_number} not merged: {result.message}")
                return False
        except Exception as e:
            logger.error(f"Failed to merge PR #{pr_number}: {e}")
            return False

    def close_pr(
        self,
        repo: str,
        pr_number: int,
        comment: Optional[str] = None,
    ) -> None:
        """Close a pull request without merging."""
        if comment:
            self.add_comment(repo, pr_number, comment)
        
        self.update_pr(repo, pr_number, state="closed")
        logger.info(f"Closed PR #{pr_number}")

    def generate_pr_title(
        self,
        issue_number: int,
        issue_title: str,
        issue_type: str = "feature",
    ) -> str:
        """Generate a PR title from issue information."""
        # Prefix based on type
        prefix_map = {
            "feature": "feat",
            "enhancement": "feat",
            "bug": "fix",
            "bugfix": "fix",
            "documentation": "docs",
            "refactor": "refactor",
            "test": "test",
        }
        
        prefix = prefix_map.get(issue_type.lower(), "feat")
        
        # Capitalize first letter of title
        title = issue_title[0].upper() + issue_title[1:] if issue_title else ""
        
        return f"{prefix}: {title} (#{issue_number})"

    def generate_pr_body(
        self,
        issue_number: int,
        issue_title: str,
        changes_summary: str,
        tasks_completed: List[str],
    ) -> str:
        """Generate a PR body from issue and changes information."""
        body_parts = [
            f"## Summary\n\n",
            f"Closes #{issue_number}\n\n",
            f"**Issue:** {issue_title}\n\n",
            f"## Changes\n\n",
            f"{changes_summary}\n\n",
        ]
        
        if tasks_completed:
            body_parts.append("## Tasks Completed\n\n")
            for task in tasks_completed:
                body_parts.append(f"- [x] {task}\n")
            body_parts.append("\n")
        
        body_parts.extend([
            "## Testing\n\n",
            "- [ ] Unit tests added/updated\n",
            "- [ ] Manual testing completed\n\n",
            "## Checklist\n\n",
            "- [ ] Code follows project conventions\n",
            "- [ ] No breaking changes\n",
            "- [ ] Documentation updated if needed\n",
        ])
        
        return "".join(body_parts)
